### ISSUE TITLE
Installation Documentation

### ISSUE THREAD

**Issue by jennifer-dela-cruz** [larsll/deepracer-for-cloud#72]
The following are found in 2 separate files. Please update the documentation.

https://larsll.github.io/deepracer-for-cloud/installation.html

Configure run.env as follows:
DR_LOCAL_S3_PROFILE=default
DR_LOCAL_S3_BUCKET=<bucketname>
DR_UPLOAD_S3_PROFILE=default
DR_UPLOAD_S3_BUCKET=<your-aws-deepracer-bucket>

**Comment by larsll** [comment]
Hi @jennifer-dela-cruz - do you mean that DR_UPLOAD_S3_BUCKET and DR_UPLOAD_S3_PROFILE is in the system.env? (Which is correct, I can update accordingly.)
