### ISSUE TITLE
DeepRacer import model require deepracer_checkpoints.json

### ISSUE THREAD

**Issue by Usin2705** [larsll/deepracer-for-cloud#77]
Discussed in slack: https://aws-ml-community.slack.com/archives/C014QJT68DV/p1598497879018700
and in AWS document: https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-troubleshooting-service-migration-errors.html

Model upload to S3 will need the deepracer_checkpoints.json file, otherwise deepracer will display error: "checkpoint does not exist"

People is the slack discussion pointed out that  you can easily fix this by open file:
[deepracer-for-cloud/scripts/upload/upload-model.sh](https://github.com/larsll/deepracer-for-cloud/blob/98c80120289a94358edc73a9b16dfbbe0e759432/scripts/upload/upload-model.sh) 
And comment out line 144:
`rm ${WORK_DIR}model/deepracer_checkpoints.json`

**Comment by larsll** [comment]
@Usin2705 - you can try to test this by checking out the fix-upload branch!

**Comment by Usin2705** [comment]
Thank you very much for your work, Lars
I tested the branch, it worked.
