### ISSUE TITLE
 Checkpoint does not exist and readlink: missing operand

### ISSUE THREAD

**Issue by jennifer-dela-cruz** [larsll/deepracer-for-cloud#79]
See screenshot below for the error encountered after uploading the model and importing it to the AWS console.

Sagemaker Logs
![image](https://user-images.githubusercontent.com/53291960/93664523-20ca5b80-faa2-11ea-9ace-525c1d90989b.png)

Upload model
![image](https://user-images.githubusercontent.com/53291960/93664483-ed87cc80-faa1-11ea-89b9-5d80594b19f4.png)

AWS Console
![image](https://user-images.githubusercontent.com/53291960/93664527-2de74a80-faa2-11ea-9b64-aeb9d2f04d27.png)

**Comment by larsll** [comment]
This one is strange; it seems like the Sagemaker deletes the latest files before the checkpoint is updated accordingly. At least error checking is needed here to avoid uploading a partial model.
